/*

 WINDOW.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 8

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char window[] =
{
  0x00, 0x21, 0x0F, 0x0B, 0x15, 0x0C, 0x19, 0x22, 0x00, 0x13, 0x18, 0x0E, 0x1F, 0x1D, 0x1E, 0x1C, 0x13, 0x0F, 0x1D
};

/* End of WINDOW.C */
